name: apps/components-demo
on:
  push:
    paths:
      - "packages/components/**"
      - "apps/components-demo/**"
      - ".github/workflows/_common_jobs.yml"
      - ".github/workflows/ci_apps_components_demo.yml"
      - "eslint.config.js"
      - "package.json"
jobs:
  build-components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i
      - name: Build components package
        run: npm run build -w @source-cooperative/components
  ci:
    needs: build-components
    uses: ./.github/workflows/_common_jobs.yml
    with:
      workspace: "@source-cooperative/components-demo"
