name: apps/viewers
on:
  push:
    paths:
      - "packages/components/**"
      - "apps/viewers/**"
      - ".github/workflows/_common_jobs.yml"
      - ".github/workflows/ci_apps_viewers.yml"
      - "eslint.config.js"
      - "package.json"
jobs:
  ci:
    uses: ./.github/workflows/_common_jobs.yml
    with:
      workspace: "@source-cooperative/viewers"
