name: packages/cli
on:
  push:
    paths:
      - "packages/cli/**"
      - ".github/workflows/_common_jobs.yml"
      - ".github/workflows/ci_packages_cli.yml"
      - "eslint.config.js"
      - "package.json"
jobs:
  ci:
    uses: ./.github/workflows/_common_jobs.yml
    with:
      workspace: "@source-cooperative/cli"
